/**
 * Simple script template that can be used as a starting point for
 * deployment scripts for generated modules.
 */
export function createDeployScriptTemplate(): string {
  return [
    "#!/usr/bin/env bash",
    "",
    "set -euo pipefail",
    "",
    "echo 'This is a placeholder deploy script generated by Unit09.'",
    "echo 'Customize it with your own deployment logic.'"
  ].join("\n");
}
