/**
 * Generate a minimal frontend stub that can be used to quickly wire a
 * module into a browser-based UI.
 */
export function createReactStub(componentName: string): string {
  return [
    "import React from 'react';",
    "",
    `export const ${componentName}: React.FC = () => {`,
    "  return (",
    "    <div>",
    `      <h1>${componentName}</h1>`,
    "      <p>This component was generated by the Unit09 core engine.</p>",
    "    </div>",
    "  );",
    "};"
  ].join("\n");
}
