import type { PipelineContext, ModuleArtifacts } from "./types";
import { addCheckpoint } from "./runFullPipeline";

/**
 * Generate basic artifacts for each module. For now this emits a single
 * README-like file per module with a short description of its contents.
 */
export async function generateModuleArtifacts(ctx: PipelineContext): Promise<PipelineContext> {
  const start = Date.now();
  const diagnostics: string[] = [];

  const project = ctx.working.project;
  const modules = ctx.working.modules ?? [];
  const artifacts: ModuleArtifacts[] = [];

  for (const module of modules) {
    const contentLines: string[] = [];
    contentLines.push(`# Module: ${module.label}`);
    contentLines.push("");
    contentLines.push("This module was generated by the Unit09 core engine.");
    contentLines.push("");
    contentLines.push("Files:");
    for (const filePath of module.filePaths) {
      contentLines.push(`- ${filePath}`);
    }

    artifacts.push({
      moduleId: module.id,
      files: [
        {
          relativePath: `unit09/${module.label}/README.md`,
          content: contentLines.join("\n")
        }
      ]
    });
  }

  ctx.working.artifacts = artifacts[0];
  diagnostics.push(`Generated artifacts for ${modules.length} modules`);

  addCheckpoint(ctx, {
    stage: "generate-artifacts",
    startedAt: start,
    completedAt: Date.now(),
    diagnostics
  });

  ctx.stage = "assemble-build-plan";
  return ctx;
}
